### ISSUE TITLE
Failed to initialize libOVR

### ISSUE THREAD

**Issue by drsnooker** [LukeRoss00/nolf2-real-mod#2]
Failed to initialize libOVR (error -3001)
OpenVR loaded: yes
Revive loaded: yes
Last error: -1004, ""

i7 4770, 8GB, 1080ti, HTC vive, win10

**Comment by LukeRoss00** [comment]
Error -3001 is "Couldn't load LibOVRRT."

Do you have the Oculus runtime installed? Was it running when you got the error?

Also, could you try downloading the mod again (I refreshed the release), so that you're using the latest version of Revive?

**Comment by drsnooker** [comment]
No oculus at all. I'll try the update!

**Comment by drsnooker** [comment]
Error message really says libOVR not OVRRT. Redownloaded. Still error -3001. Added +vrrevive 1. Same error

**Comment by LukeRoss00** [comment]
Yes, it's "Failed to initialize libOVR", but error -3001 means "Couldn't load LibOVRRT."

You need the Oculus runtime on your system. The other users that reported success had it installed. I believe that you don't need to register an account with Oculus, but you do need to install the runtime.

**Comment by LukeRoss00** [comment]
Revive official instructions say:

1. Install [Oculus Home](https://www.oculus.com/en-us/setup/) and skip the first-time setup.

**Comment by drsnooker** [comment]
That did it! Reinstalled oculus and revive now running. Figuring out how to move etc... wands don't seem to do anything.
