### ISSUE TITLE
Game does not lock mouse.

### ISSUE THREAD

**Issue by thegforcian** [LukeRoss00/nolf2-real-mod#4]
When entering game clicking causes the game to lose the mouse focus.  Sound cuts off and the mouse interacts with other applications while the user is in VR unable to use the mouse.

**Comment by LukeRoss00** [comment]
Sorry, I'm only seeing this today. Does that happen only if you click very quickly outside the game window at startup?

**Comment by LukeRoss00** [comment]
I'm closing this as inactive, feel free to reopen it if you have new information

**Comment by thegforcian** [comment]
Sorry I just re-opened the game recently and noticed I was still having the issue.  There is no game window outside of VR, like the window for the game just doesn't open on the monitor.
