### ISSUE TITLE
But I have the Vive on a linux system

### ISSUE THREAD

**Issue by frostworx** [LukeRoss00/nolf2-real-mod#5]
tbh I don't know the game and just recently found your promising VR mod.
thanks a lot for your hard work!
Any chance you know which oculus runtime is required as minimum for the bundled Revive?
I'm using linux here and very many win-only (vr) games works excellent ootb using steam built-in steamplay.
Not sure if revive is even supposed to work in general under linux via steamplay, but I can't even try with the latest runtime, as it doesn't offer an offline install and the online installer crashes when trying to install.
(DeviceIoControl  fails and therefore the installer doesn't find a valid place to install).
would be great if you could help :)

**Comment by LukeRoss00** [comment]
Thank you for the kind words. The mod was built against version 1.20 of the Oculus SDK, so any version of the runtime down to 1.20 (November 2017) should be fine for the embedded Revive.

I have no experience at all with Steam Play however, so I'm afraid I can't help you there. Please report back your results though!

**Comment by frostworx** [comment]
thank you for the quick and friendly reply! :)
afaik runtime 0.8 was the last version with an offline installer, but in case I get it running I'll let you know of course.
